spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
  devtools:
    livereload:
      enabled: true
    freemarker:
      cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: false
      ddl-auto: update
    defer-datasource-initialization: true
  http:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
#  config:
#    activate:
#      on-profile: dev


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


cloud:
  aws:
    credentials:
      accessKey: AKIAVIUCCJXTWKCZD4P5
      secretKey: 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
    s3:
      bucket: chanho
    region:
      static: ap-northeast-2
    stack:
      auto: false


